### ISSUE TITLE
Reified functions don't show up in API dump

### ISSUE THREAD

**Issue by zsmb13** [Kotlin/binary-compatibility-validator#35]
Inline functions work as expected, but if they also have reified type parameters, they don't show up in the API dump output (presumably because there isn't a regular, callable method generated, just a synthetic one)

An example project showcasing this is available [here](https://github.com/zsmb13/binary-compat-reified-issue/blob/master/api/kotlin-gradle-starter.api), see the [`Main.kt`](https://github.com/zsmb13/binary-compat-reified-issue/blob/master/src/main/kotlin/Main.kt) and [`kotlin-gradle-starter.api`](https://github.com/zsmb13/binary-compat-reified-issue/blob/master/api/kotlin-gradle-starter.api) files for the discrepancy.

**Comment by zsmb13** [comment]
Found the commit https://github.com/Kotlin/binary-compatibility-validator/commit/3f13d12953c24ad1181c21cc6b093438efd67ad1 that disabled this. I'll look into having reified functions optionally included, as that would be really useful for many libraries.

**Comment by qwwdfsad** [comment]
Indeed, reified functions do not show up in the API dump because they are not part of public ABI (e.g. removing it won't break any previously compiled code) and this tool is intended to keep track of binary compatibility, not source one.

Regular inline functions are part of ABI: they can be called reflectively (reified function cannot because they are guarded by `Intrinsics.reifiedOperationMarker`) or from Java as regular functions

**Comment by zsmb13** [comment]
So it's not even worth adding a flag for this in this project, to dump them in the output optionally?

How would you check that sort of source compatibility then? With another tool on top of this one?

**Comment by qwwdfsad** [comment]
>So it's not even worth adding a flag for this in this project

Exactly, because it's out of the scope of this project.

>How would you check that sort of source compatibility then? 

We do not check that automatically, only by carefully studying the changes. 

We've seriously considered adding some kind of "source compatibility tool", but it's neither possible nor makes sense because for almost _any_ change in the source there exists a manually crafted piece of code that either breaks or changes its behaviour. So the tool would either trigger error on each public API change (then it's not useful at all), or skip a lot of potentially breaking changes.

>for almost _any_ change in the source there exists a manually crafted piece of code that either breaks or changes its behaviour

Also, this is one of the reasons why auto-imported `kotlin` package from stdlib has the lowest priority in overload resolution
