### ISSUE TITLE
Add ability to include packages, classes, classes annotated by specific annotation. 

### ISSUE THREAD

**Issue by nevack** [Kotlin/binary-compatibility-validator#63]
For now, plugin only allows to ignore some packages, projects, classes and classes annotated with some annotation.

But some projects may want to include classes in Public API, if they are annotated with some annotation, that marks it's explicitly public.

**Comment by qwwdfsad** [comment]
It would be nice to see the motivated use-cases for such API. On the first glance, such package/modules design seems at least questionable (e.g. "this whole package is not part of public API _except_ this particular class").

Apart from conceptual reasons, this feature will complicate our maintenance and correctness, because it's much easier to exclude something from scanning than to include it from partially excluded sources. Weird interactions during the intersections of exclusions/inclusions rules and their nom-orthogonality come as a bonus here.
