### ISSUE TITLE
Top-level projects don't seem to work on all OS's 

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/binary-compatibility-validator#76]
I'm not entirely sure if I'm reading this all right, but in our single-project repo doesn't appear to work when running `apiCheck` on linux CI while it does work on macOS locally.

Here's a repro - https://github.com/slackhq/EitherNet/pull/52. Fails on CI with a strange check that suggests it's expecting a subproject, but it's a single-project repo only.

**Comment by joffrey-bion** [comment]
Why do you say it seems to be expecting a subproject? From your repro I could see:

```
Execution failed for task ':apiCheck'.
> File eithernet.api is missing from api/, please run :eithernet:apiDump task to generate one
```

Since you do have [api/EitherNet.api](https://github.com/slackhq/EitherNet/blob/main/api/EitherNet.api) (with CamelCase), I wonder if it's a case issue instead. Did `apiDump` generate the file with this camel case?

Maybe the bug would be due to an inconsistency between `.api` files generation and inspection. The former respecting the case of the project name, and the latter expecting all lowercase?

**Comment by ZacSweers** [comment]
This only reproduces on Linux, nothing errors when trying this flow on macOS locally.

Look again at the message

```
please run :eithernet:apiDump task
```

This doesn't make sense because there _is_ no `eithernet` subproject. There is only one project — the root project. The only dump task is `:apiDump`, not `:eithernet:apiDump`. I think the problem lies somewhere in there - why does the plugin think that subproject exists?

**Comment by ZacSweers** [comment]
It could be that it expects an all lowercase name on Linux, but I would expect the error message to be different or to possibly just better handle this case

**Comment by joffrey-bion** [comment]
> This doesn't make sense because there is no eithernet subproject [...] I think the problem lies somewhere in there - why does the plugin think that subproject exists?

Oh right, the error message indeed looks broken in this respect. But looking at the code it really seems it is just that - a misleading error message. However, I'm not the maintainer of this project, so please take that with a grain of salt.

> This only reproduces on Linux, nothing errors when trying this flow on macOS locally.

Filename case sensitivity behaving differently on different systems wouldn't surprise me. Better have the correct case instead of relying on system quirks.

IMO the problem is that you ran `apiDump` with the default project name, and later added an explicit `rootProject.name` in the Gradle settings without regenerating the api files again.

Did you try running `:apiDump` again as I suggested? Did it generate the file with lowercase name? If macOS considers the filename to be the same, it might not be enough to just run `apiDump`, you might need to delete the file first to be sure it re-creates it with proper case.

**Comment by ZacSweers** [comment]
> Did you try running :apiDump again as I suggested?

Yes, mentioned above too. No errors locally and no local file changes after running.

**Comment by joffrey-bion** [comment]
> Yes, mentioned above too

You mentioned "trying this flow", I wasn't sure whether this referred to `apiCheck` or `apiDump`, and since you made no mention of the effect (or non effect) on the api file, I assumed you were referring to `apiCheck` working fine locally but failing on linux CI.

> No errors locally and no local file changes after running.

Did you try deleting/renaming the file first? Does it stay lowercase after that? If your OS doesn't distinguish files that differ only by case, it's expected it might consider the camel case file as an already existing version of the lowercase file.

**Comment by qwwdfsad** [comment]
Thanks for the report! Case sensitive may be the case here as OS X FS is case-insensitive (i.e. `Foo.txt` and `foo.txt` are considered to be the same name), I'll investigate

**Comment by qwwdfsad** [comment]
Seems it wasn't fully fixed an requires further investigation: https://github.com/Kotlin/binary-compatibility-validator/pull/79#issuecomment-1104337650
